### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by chanceaclark** [Pier1/rocketbelt#150]
play-circle-o w/i pause-circle-o
Example: https://iconmonstr.com/video-15/

**Comment by chanceaclark** [comment]
Calendar Icon

**Comment by kendrick** [comment]
1.13.0 has `rb-icon-calendar-add`. Should be able to add updated play/pause icons in the next minor release.

**Comment by kendrick** [comment]
Update the play/pause icons (finally) in aa0cce6. Will be in the next RB release.
