### ISSUE TITLE
color(gray, plus5) throws an error

### ISSUE THREAD

**Issue by sklingler93** [Pier1/rocketbelt#158]
According to the docs, grayscale color variants should range from `plus5` to `minus2`.

```background-color: color(gray, plus5);```

Results in

``` >> Error: Color variant `plus5` does not exist in family `gray`.
    >>         on line 16 of ../pier1_core/cartridge/css/vendor/rocketbelt/tools/functions/_color.scss
    >> >>       @error 'Color variant `#{$variant}` does not exist in family `#{$family}```

However, `plus4` through `minus2` work fine.

**Comment by kendrick** [comment]
Have you synced with upstream recently? `plus5` was added as a new variant a while back and is being used to [render styles for tables](https://github.com/Pier1/rocketbelt/blob/402f0fdade33af2402c68662a37255678ceabb9c/rocketbelt/components/tables/_tables.scss#L42).

**Comment by sklingler93** [comment]
I was running `1.13.2` but upgrading to `1.13.4` did not resolve the issue

**Comment by kendrick** [comment]
I think this may be a combination of `.npmignore` being too greedy and one of the Gulp tasks not copying Sass files to the right place. Investigating…
