### ISSUE TITLE
Busy indicators destroy JS bindings

### ISSUE THREAD

**Issue by sklingler93** [Pier1/rocketbelt#178]
### Summary

The Rocketbelt busy indicators destroy JS bindings because the innerHTML is replaced.

### Steps to reproduce

1. Add JS bindings (event handlers or Knockout) to an element
2. Add the `.is-busyable` and `.is-busy` classes
3. Attempt to trigger the JS bindings

### What is the current *bug* behavior?

After adding the `.is-busy` class to an element that has JS event listeners or is Knockout bound, all the bindings are lost.

### What is the expected *correct* behavior?

All bindings still work after using a busy indicator.

### Possible fixes

Replace `.innerHTML` with `.insertAdjacentHTML`

**Comment by kendrick** [comment]
Fixed by #179.
