### ISSUE TITLE
Gradient Easing

### ISSUE THREAD

**Issue by chanceaclark** [Pier1/rocketbelt#194]
Gradients on full-bleed cards seem to be harsh when content is smaller. I'd like to propose a more percise easing function using an ease-in-out-sine approach like so:

```sass
@function ease-gradient($gradient-to-color) {
  $run: '';
  $percentages: 0%, 19%, 34%, 47%, 56.5%, 65%, 73%, 80.2%, 86.1%, 91%, 95.2%, 98.2%, 100%;
  $alphas: 1, .738, .541, .382, .278, .194, .126, .075, .042, .021, .008, .002, 0;
  @each $percentage in $percentages {
    $i: index($percentages, $percentage);
    $alpha: nth($alphas, $i);

    $run: '#{$run} #{hsla(hue($gradient-to-color), saturation($gradient-to-color), lightness($gradient-to-color), $alpha) $percentage}';
    @if $i != length($percentages) {
      $run: '#{$run},';
    }
  }
  @return $run;
}
``` 

**Example:**
![image](https://user-images.githubusercontent.com/10539418/39155937-bc00cc5e-4719-11e8-9440-070f113c78fe.png)

Concepts taken from [this CSS Tricks article](https://css-tricks.com/easing-linear-gradients/#post-254506).

**Comment by kendrick** [comment]
We can definitely take a second look at this. The CSS Tricks article is greatness and was the inspriation for what's in RB today. A "normal" `ease-in-out` gradient looks much more pleasant than RB's gradient, but the text being scrimmed gets blown out without a _massive_ amount of top padding (in the `5rem` range).

An easing function in between the two may be a good middle ground, along with a little bit of `padding-top`.

**Comment by kendrick** [comment]
(On that note there are a bunch of easing functions in [_ease.scss](https://github.com/Pier1/rocketbelt/blob/cc86c2af923062916c1481dbb5bdb63856daf88b/rocketbelt/tools/functions/_ease.scss) if you want to play around.)
