### ISSUE TITLE
Progress Indicators throws errors when elements are undefined

### ISSUE THREAD

**Issue by thousandknives** [Pier1/rocketbelt#197]
The following lines are failing when the DOM lookup doesn't find an element. Simple fix is to add some null-checking.

[rocketbelt.progress-indicators.js
](https://github.com/Pier1/rocketbelt/blob/develop/rocketbelt/components/busy-indicators/rocketbelt.progress-indicators.js)
**Line 45**
`el.querySelector('.flip-loader').classList.add('is-busy_message-shown');`

**Line 63**
`el.querySelector('.is-busy_overlay').classList.add('is-busy_overlay-opaque');`

**Comment by kendrick** [comment]
Any chance you can PR this? If so I can get it merged in when I'm back on
wifi tomorrow or Wednesday, in time for the release.

**Comment by thousandknives** [comment]
Yeah I should have some free time this morning
