### ISSUE TITLE
Card grid sizing

### ISSUE THREAD

**Issue by sliptype** [Pier1/rocketbelt#200]
We noticed that when adjusting the padding on `.card-grid_item` the grid item sizing can break.

The card grid demo uses `p` as the content of `.card-grid_item` which has a bottom margin applied by the user agent stylesheet. If that is removed:

![margin](https://i.imgur.com/EnNANGZ.png)

And the padding on `.card-grid_item` is adjusted, to say 1rem:

![padding](https://i.imgur.com/YdQAymx.png)

After running `rb.cardGrids.resizeAllGridItems('.card-grid')` the resulting grid sizing is incorrect:

![result](https://i.imgur.com/3g8zHoH.png)

I believe this might be because the padding is being subtracted from the height of the content. https://github.com/Pier1/rocketbelt/blob/7eff8a1193236710135c84e137fffdca1724227a/rocketbelt/components/card-grids/rocketbelt.card-grids.js#L21

Shouldn't the padding be added to account for the total height of the content?

**Comment by kendrick** [comment]
Yup, pretty sure that's a typo. I'll fix it today.

**Comment by kendrick** [comment]
This is fixed in the development branch & will be published tomorrow along with a couple of unrelated changes. Thanks for the heads up @sliptype!
