### ISSUE TITLE
Custom event does not fire when tabcordion is used via keyboard

### ISSUE THREAD

**Issue by pmenh** [Pier1/rocketbelt#201]
rb.tabcordions.js has an event firing for 
$navlist.on('click', '.tabcordion_nav-item .tabcordion_nav-trigger', function ()

We are using that event to resize the reviews tab on product set products. There is no event firing for keydown, so the reviews won't get resized.

**Comment by kendrick** [comment]
Great catch, I can look into this.

**Comment by kendrick** [comment]
Fixed via 9184a356405a19940126699de87f1b4e957c31f9.

**Comment by kendrick** [comment]
@pmenh, when you have a minute can you verify that what's in develop does what you need it to? Thanks!

**Comment by pmenh** [comment]
Hey I just got in the office. Car died this morning :\
Yeah that should do it! Hopefully TFS gets fixed soon so we can test with the latest code. Thanks!
