### ISSUE TITLE
Using forEach on nodeList type is not supported on IE and Edge

### ISSUE THREAD

**Issue by pmenh** [Pier1/rocketbelt#202]
rocketbelt.card-grids.js is using querySelectorAll() which returns a NodeList type. NodeList is incompatible with IE and Edge.

![image](https://user-images.githubusercontent.com/27689422/44935657-3e032480-ad37-11e8-81df-7cf4bcb4f93b.png)

**Comment by kendrick** [comment]
All browsers have basic support for `NodeList`, but IE (and Edge pre-16,
IIRC) definitely doesn't support `NodeList.forEach()`. RB includes a
polyfill in rocketbelt.js, so be sure that's included on the page and you
should be good to go.

**Comment by sliptype** [comment]
https://github.com/Pier1/rocketbelt/blob/edecd8b466cc4c135ff3d59c9b34ebb1ae034bc6/rocketbelt/base/rocketbelt.js#L161

`NodeList.protoype.forEach` is being polyfilled as `NodeList.prototype.foreach` (lowercase e) so the invocation in `rocketbelt.card-grids.js` is breaking in IE11. 

I think the best approach is to fix the polyfill, we'll make a PR
